"use client";
import { useMemo,useState } from "react";
import NavTabs from "@/components/NavTabs";
import { Card,Kpi,ProductList,Empty } from "@/components/Shared";
import { bad, good, markData, merge, pct, rank, shopSummary, split, totals, won } from "@/lib/mark";

function StoreList({title,rows,positive}:{title:string;rows:any[];positive:boolean}){return <div className="rounded-2xl bg-slate-50 p-4"><h3 className="mb-3 font-black">{title}</h3><div className="space-y-3">{rows.map((r,i)=><div key={r.storeName} className="flex items-center justify-between rounded-xl bg-white p-3"><div><p className="text-xs text-slate-500">#{i+1}</p><p className="font-bold">{r.storeName}</p></div><div className="text-right"><p className={`font-black ${positive?"text-blue-600":"text-red-600"}`}>{r.weekChangeRate>=0?"+":""}{pct(r.weekChangeRate)}</p><p className="text-xs text-slate-500">{won(r.weekSales)}</p></div></div>)}</div></div>}
function BarList({rows,field}:{rows:any[];field:string}){const max=Math.max(1,...rows.map(r=>Number(r[field]||0)));return <div className="max-h-[520px] space-y-4 overflow-y-auto pr-2">{rows.length===0&&<Empty/>}{rows.map(r=>{const v=Number(r[field]||0);const prev=field==="daySales"?r.compareDaySales:r.compareWeekSales;const ch=field==="daySales"?r.dayChangeRate:r.weekChangeRate;return <div key={r.storeName}><div className="mb-1 flex justify-between gap-3 text-xs text-slate-500"><span className="font-semibold text-slate-700">{r.storeName}</span><span>{won(v)}</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-900" style={{width:`${Math.max(4,v/max*100)}%`}}/></div><p className="mt-1 text-xs text-slate-500">전주 {won(prev)} · 전주비 {ch>=0?"+":""}{pct(ch)}</p></div>})}</div>}

export default function MarkDashboard({active}:{active:"daily"|"weekly"|"monthly"}){
 const [store,setStore]=useState(markData.weekly.productStoreNames?.[0]||"");
 const pd=markData[active];
 const merged=active==="monthly"?merge(pd.current, pd.compare, pd.year):merge(pd.current,pd.compare);
 const {core,shop}=split(merged); const t=totals(core); const shops=shopSummary(shop);
 const field=active==="daily"?"daySales":active==="monthly"?"monthSales":"weekSales";
 const rows=rank(core,field); const storeProducts=useMemo(()=>markData.weekly.storeTopProducts?.[store]||[],[store]);
 return <main className="min-h-screen p-6"><div className="mx-auto max-w-7xl space-y-6">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-3xl font-bold tracking-tight">오프라인 매출 리뷰 대시보드(소재천) Mark2.7</h1><p className="mt-1 text-sm text-slate-500">{active==="daily"?"일간 · 일_전일 vs 일_전주":active==="weekly"?"주간 · 상품/재고 연결":"월간 · 위탁 제외 핵심매장 중심"}</p></div><NavTabs active={active}/></header>
  <section className="rounded-3xl bg-slate-900 p-4 text-sm font-bold text-white shadow-sm">{pd.periodLabel}</section>
  <section className="grid gap-4 md:grid-cols-4">{active==="daily"?<><Kpi t="일 목표" v={won(t.dayTarget)}/><Kpi t="일 매출" v={won(t.daySales)} s={`전주 동요일 대비 ${pct(t.dayChange)}`}/><Kpi t="일 달성률" v={pct(t.dayRate)}/><Kpi t="월 누적 매출" v={won(t.monthSales)} s={pct(t.monthRate)}/></>:active==="weekly"?<><Kpi t="주간 목표" v={won(t.weekTarget)}/><Kpi t="주간 매출" v={won(t.weekSales)} s={`전주 대비 ${pct(t.weekChange)}`}/><Kpi t="주간 달성률" v={pct(t.weekRate)}/><Kpi t="월 누적 매출" v={won(t.monthSales)} s={pct(t.monthRate)}/></>:<><Kpi t="월 목표" v={won(t.monthTarget)}/><Kpi t="월 누적 매출" v={won(t.monthSales)} s={`전월 대비 ${pct(t.monthChange)}`}/><Kpi t="월 달성률" v={pct(t.monthRate)}/><Kpi t="전년동월 대비" v={pct(t.yearMonthChange)}/></>}</section>
  {active==="weekly"&&<section className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">이번 주 한 줄 결론</h2><p className="mt-3 text-slate-700">핵심 매장 기준 주간 매출은 전주 대비 {t.weekChange>=0?"성장":"하락"}했습니다. 호조 매장은 판매 포인트를 공유하고, 부진 매장은 상품 구성과 재고 보강을 점검하세요.</p></section>}
  {active!=="monthly"&&<section className="grid gap-6 lg:grid-cols-2"><Card t="매출관리 필요매장"><div className="grid gap-4 md:grid-cols-2"><StoreList title="호조 매장 TOP3" rows={good(core)} positive/><StoreList title="부진 매장 TOP3" rows={bad(core)} positive={false}/></div></Card><Card t={active==="daily"?"매장별 일매출 순위":"매장별 주간 매출 순위"}><BarList rows={rows} field={field}/></Card></section>}
  {active==="weekly"&&<section className="grid gap-6 lg:grid-cols-2"><Card t="전사 TOP 상품"><ProductList items={markData.weekly.companyTopProducts||[]}/></Card><Card t="점포별 TOP 상품" right={<select className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold" value={store} onChange={e=>setStore(e.target.value)}>{markData.weekly.productStoreNames?.map((n:string)=><option key={n}>{n}</option>)}</select>}><ProductList items={storeProducts}/></Card></section>}
  {active==="monthly"&&<section className="grid gap-6 lg:grid-cols-2"><Card t="월간 매출 리뷰"><ul className="space-y-3 text-sm leading-6 text-slate-700"><li>• 위탁/샵인샵 제외 핵심 매장의 월 누적 매출은 {won(t.monthSales)}이며 월 목표 대비 {pct(t.monthRate)}입니다.</li><li>• 전월 대비 {pct(t.monthChange)}, 전년동월 대비 {pct(t.yearMonthChange)} 흐름입니다.</li></ul></Card><Card t="월간 운영 제안"><ul className="space-y-3 text-sm leading-6 text-slate-700"><li>• 전월 대비 역신장 매장은 상품 구성과 진열을 우선 점검하세요.</li><li>• 전년동월 대비 역신장 매장은 상권 변화와 운영 이슈를 함께 확인하세요.</li></ul></Card></section>}
  <section className="grid gap-6 lg:grid-cols-2"><Card t="위탁 판매 현황"><div className="grid gap-4 md:grid-cols-2"><StoreList title="위탁 호조 TOP3" rows={shops.slice(0,3)} positive/><StoreList title="위탁 부진 TOP3" rows={[...shops].reverse().slice(0,3)} positive={false}/></div></Card><Card t="위탁채널 상품 제안"><div className="space-y-3 text-sm leading-6 text-slate-700"><p>• 전사 TOP 상품과 점포별 TOP 상품을 기준으로 위탁채널 투입 후보를 검토하세요.</p><p>• 재고CTRL에서 온/오프 가용재고를 반영한 물류 추가 할당 후보를 확인하세요.</p></div></Card></section>
 </div></main>
}
